apiVersion: v1
kind: Service
metadata:
  name: go-web-application
  labels:
    app: go-web-application
spec:
  type: ClusterIP
  selector:
    app: go-web-application
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
